apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  ports:
    - port: 8086
      protocol: TCP
      targetPort: 8086
  selector:
    app: notification-service
  type: LoadBalancer