--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  annotations: 
    deployment.kubernetes.io/revision: "1"
  labels: 
    app: notification-service
  name: notification-service
  namespace: default
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: notification-service
  strategy: 
    rollingUpdate: 
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template: 
    metadata: 
      labels: 
        app: notification-service
    spec: 
      containers: 
        - image: "urosvesic/notification-service:0.0.3-SNAPSHOT"
          imagePullPolicy: IfNotPresent
          name: notification-service
          env:
            - name: PROD_DB_HOST
              valueFrom:
                configMapKeyRef :
                  name: notification-db-config
                  key: PROD_DB_HOST
            - name: PROD_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: notification-db-config
                  key: PROD_DB_NAME
            - name: PROD_DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: notification-db-config
                  key: PROD_DB_USERNAME
            - name: PROD_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: notification-db-config
                  key: PROD_DB_PORT
            - name: PROD_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: notification-db-config
                  key: PROD_DB_PASSWORD
            - name: JWT_ISSUER_URI
              value: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_WEmesG720
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: notification-service
  name: notification-service
  namespace: default
spec:
  ports:
    - port: 8086
      protocol: TCP
      targetPort: 8086
  selector:
    app: notification-service
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion : v1
kind : ConfigMap
metadata:
  name: notification-db-config
data:
  PROD_DB_HOST: containers-us-west-125.railway.app
  PROD_DB_NAME: test
  PROD_DB_PORT: "6160"
  PROD_DB_USERNAME: mongo
  PROD_DB_PASSWORD:
  

